name: CI

on:
  # NB: this differs from the book's project!
  # These settings allow us to run this specific CI pipeline for PRs against
  # this specific branch (a.k.a. book chapter).
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
    
jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  build:
        runs-on: ubuntu-latest
        steps:
        # install QEMU
            - name: Install QEMU
              run: sudo apt update && sudo apt install -y qemu-system-x86
            - name: "Print QEMU Version"
              run: qemu-system-x86_64 --version
            - uses: actions/checkout@v4
            - name: Get Nightly Build
              run: rustup override set nightly
            - name: Add rust-src
              run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
            - name: Add llvm-tools 
              run: rustup component add llvm-tools-preview
            - name: Install Bootimage
              run: cargo install bootimage
            - name: Build
              run: cargo build --target x86_64-os.json --verbose
            - name: Run tests
              run: cargo test --target x86_64-os.json --verbose
  clippy:
        runs-on: ubuntu-latest
        steps:
        # install QEMU
            - name: Install QEMU
              run: sudo apt update && sudo apt install -y qemu-system-x86
            - name: "Print QEMU Version"
              run: qemu-system-x86_64 --version
            - uses: actions/checkout@v4
            - name: Get Nightly Build
              run: rustup override set nightly
            - name: Add rust-src
              run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
            - name: Add llvm-tools 
              run: rustup component add llvm-tools-preview
            - name: Install Bootimage
              run: cargo install bootimage
            - name: Install nightly clippy
              run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
            - name: Run Clippy
              run: cargo clippy --target x86_64-os.json --verbose
